services:

  # Comentar o db para rodar localmente, e descomentar a linha do MYSQL_HOST no api
  db:
    image: mysql:8.1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: teste
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build: .
    restart: on-failure 
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app:cached
    ports:
      - '8000:8000'
    environment:
      DJANGO_DEBUG: 'True'
      DJANGO_SECRET_KEY: 'django-insecure--2t-+s1b4+qu!5#je@%v&v_tp(7pr#5mb^r4s989hoj(0*nuhg'
      DJANGO_ALLOWED_HOSTS: 'localhost,127.0.0.1,0.0.0.0'
      MYSQL_DATABASE: teste
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      # MYSQL_HOST: host.docker.internal
      MYSQL_PORT: '3306'


    depends_on:
      - db

volumes:
  db_data:
