# Generated by Django 6.0.5 on 2026-05-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('ALTA', 'Prioridade Alta'), ('MEDIA', 'Prioridade Média'), ('BAIXA', 'Prioridade Baixa')], default='MEDIA', max_length=50),
        ),
    ]
