# Generated by Django 6.0.5 on 2026-05-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='priority',
            field=models.CharField(choices=[('ALTA', 'Prioridade Alta'), ('MEDIA', 'Prioridade Média'), ('BAIXA', 'Prioridade Baixa')], default='MEDIA', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Status pendente'), ('EM_PROGRESSO', 'Status em progresso'), ('CONCLUIDO', 'Status concluido')], default='PENDENTE', max_length=50),
        ),
    ]
